Avatarコンポーネントを作る
actier-luchta/cuv pull request #133
Opened 2023-06-02 02:08 UTC by kondoriyo

#113 

Avatarコンポーネントを作成しました。

<img width="1236" alt="スクリーンショット 2023-06-02 11 02 42" src="https://github.com/actier-luchta/cuv/assets/101681088/d974ad23-b269-4d7b-bf89-654c7ba67b0d">

2023-06-02 04:54 UTC, kbtaniguchi requested changes

2023-06-02 04:54 UTC, kbtaniguchi commented on src/components/images/CAvatar.story.vue
> +| color | 'white' / 'black' / 'light' / 'dark' / 'primary' / 'link' / 'success' / 'danger' / 'warning' / 'info' | undefined | 色を指定します |
ドキュメント上のUnionTypeの書き方って `/` にしてましたっけ？TSと同じ表記で `|` 使うのが良いと思います。

2023-06-02 04:54 UTC, kbtaniguchi commented on src/components/images/CAvatar.story.vue
> +| rounded | string / number / boolean | false | コンポーネントの`border-radius`を指定します |
roundedに何を渡したらどう表示されるのか分からないので、
https://vuetifyjs.com/en/styles/border-radius/
↑を参考によく使いそうな `none | small | medium | large | x-large | pill | circle` あたりを対応するようにしましょうか

2023-06-02 04:54 UTC, kbtaniguchi commented on src/components/images/CAvatar.story.vue
> +| size | string/number | "medium" | サイズを指定します。`x-small`, `small`, `medium`, `large`, `x-large`で指定もできます。 |
ここも `string | number` じゃなくて `x-small`, `small`, `medium`, `large`, `x-large` だけを受け取るようにしちゃいましょう

2023-06-02 04:56 UTC, kondoriyo commented on src/components/images/CAvatar.story.vue
> +| color | 'white' / 'black' / 'light' / 'dark' / 'primary' / 'link' / 'success' / 'danger' / 'warning' / 'info' | undefined | 色を指定します |
`|`を使うと、テーブルのセルとして、区切られてしまい、
使えませんでした、、他の書き方など、良い方法はありますでしょうか？

2023-06-02 06:18 UTC, kondoriyo commented on src/components/images/CAvatar.story.vue
> +| rounded | string / number / boolean | false | コンポーネントの`border-radius`を指定します |
avatarは正方形にroundedをつけているので、
`pill`と`circle `は形が同じになると思うので、
`pill `のみ無くしました🙇‍♀️

2023-06-05 01:30 UTC, kbtaniguchi approved these changes

2023-06-05 04:39 UTC, merged